image : mcr.microsoft.com/dotnet/sdk:3.1

stages:
  - ci

build-job:
  stage: ci
  script:
    - |
      dotnet tool install Nuke.GlobalTool --global
      nuke -Solution BrunelUni.IntelliFarm.sln
      nuke -Solution BrunelUni.IntelliFarm.Data.sln