name: Build and Push
on:
  push:
    branches: [ trunk ]
jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Install Nuke
        run: dotnet tool install Nuke.GlobalTool --global
      - name: Nuke It
        run: |
          nuke -Solution BrunelUni.IntelliFarm.sln
          nuke -Solution BrunelUni.IntelliFarm.Data.sln